### ISSUE TITLE
Broken volume up key

### ISSUE THREAD

**Issue by ceribik** [cvuchener/k90-linux-driver#4]
Not sure if this is the same driver as the one in linux 4.4 but if so it broke my volume up key.

It no longer reports a scancode, yet is somehow able report a keycode of 721 (using scankey).

See https://bbs.archlinux.org/viewtopic.php?pid=1604409#p1604409

**Comment by cvuchener** [comment]
Volume Up use the same usage code as G18 (0xe9) and I forgot to test the usage page when remapping, so I think the driver is treating it as G18. That should be an easy fix.

**Comment by cvuchener** [comment]
The latest commit (5f447e3) fixes this for me. Can you confirm it works before I send a patch to the LKML?

**Comment by ceribik** [comment]
I might be able to test in the next day or so. Will let you know.

**Comment by nandryshak** [comment]
@cvuchener Yes, that works. Thanks for the quick fix!

**Comment by ceribik** [comment]
Confirmed fixed as well. Please let us know which mainline kernel version it gets accepted into.

**Comment by cvuchener** [comment]
The patch has been merged in Linus' tree : https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=d66435cc7da95964cb386674bd82ec12ca66320a

It should be available in the first 4.6 rc (not yet tagged).

**Comment by ceribik** [comment]
Has this been merged yet? I'm on 4.6.3 and I still have to recompile the module myself, otherwise the volume up/down keys don't work.

**Comment by cvuchener** [comment]
Yes, it has been merged (see the commit linked above). And I checked: [mainline 4.6.3 contains the patched line](https://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/tree/drivers/hid/hid-corsair.c?id=refs/tags/v4.6.3#n598).

I did not update my fedora recently, but it should have 4.6 now, I will test that.

**Comment by cvuchener** [comment]
I removed my dkms module and updated my kernel to 4.6.3 (from fedora 24), and it works for me.

**Comment by ceribik** [comment]
Confirmed fixed.
